// Code generated by SQLBoiler 3.6.1 (https://github.com/volatiletech/sqlboiler). DO NOT EDIT.
// This file is meant to be re-generated in place and/or deleted at any time.

package models

var TableNames = struct {
	Foods      string
	GormFoods  string
	GormOrders string
	GormUsers  string
	Orders     string
	Users      string
}{
	Foods:      "foods",
	GormFoods:  "gorm_foods",
	GormOrders: "gorm_orders",
	GormUsers:  "gorm_users",
	Orders:     "orders",
	Users:      "users",
}
